<?php

/**
 * Implements hook_form_FORM_ID_alter().
 */
function mail_auth_form_user_login_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  // Adding custom validation...
  array_unshift($form['#validate'], 'mail_auth_extra_validate');

  // Overriding titles & descriptions...
  $form['name']['#title'] = t('Username / Email');
  $form['name']['#description'] = t('Enter your username or email address');
  $form['pass']['#description'] = t('Enter your password');
}

/*
 * Custom form validation
 */
function mail_auth_extra_validate($form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $login_input = $form_state->getValue('name');

  if (filter_var($login_input, FILTER_VALIDATE_EMAIL)) {
    $user = user_load_by_mail($login_input);

    if ($user) {
      $form_state->setValue('name', $user->getAccountName());
    }
  }
}
