<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function register_role_selection_form_user_register_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $configRoles = Drupal::configFactory()->get('register_role_selection.admin_settings')->get('roles');

  if (!empty($configRoles)) {
    $roles = [];

    foreach ($configRoles as $role) {
      $roles[$role] = $role;
    }

    $form['role'] = [
      '#type' => 'select',
      '#title' => t('Role'),
      '#description' => t('Select role'),
      '#options' => $roles,
      '#weight' => 3,
      '#required' => TRUE,
    ];

    $form['#validate'][] = '_register_role_selection_validate_form';
  }

  return $form;
}

/**
 * Provides custom registration validation for inserting selected role.
 */
function _register_role_selection_validate_form(array &$form, FormStateInterface $form_state): void {
  $form_state->setValue('roles', [$form_state->getValue('role')]);
}

